# Generated by Django 6.0.2 on 2026-02-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='ejari_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='ejari_image',
            field=models.ImageField(blank=True, null=True, upload_to='ejaris/'),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='ejari_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='custom_user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
