# Generated by Django 6.0.2 on 2026-02-18 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custom_user_created_at_custom_user_ejari_expiry_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='country',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='zip_code',
        ),
    ]
