# Generated by Django 6.0.2 on 2026-03-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_custom_user_picture_alter_custom_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='user_type',
            field=models.CharField(choices=[('RIDER', 'Rider'), ('TENANT', 'Tenant')], default='RIDER', max_length=10),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='license_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
