# Generated by Django 6.0.2 on 2026-03-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_custom_user_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom_user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff'), ('manager', 'Manager')], default='staff', max_length=20),
        ),
    ]
