# Generated by Django 6.0.2 on 2026-03-12 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_pay', models.DecimalField(decimal_places=2, max_digits=10)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('experience', models.IntegerField()),
                ('work_location', models.CharField(max_length=100)),
                ('salary_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('maid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maids', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
