# Generated by Django 6.0.2 on 2026-03-12 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0002_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='rider',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'RIDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bikes', to=settings.AUTH_USER_MODEL),
        ),
    ]
